name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22
      id: go
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: make gz
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ibugtool
          ibugtool.gz
