name: Build

on:
  - push

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24
      id: go
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: make test
    - name: Build
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: build --clean --snapshot
    - uses: goreleaser/goreleaser-action@v6
      if: startsWith(github.ref, 'refs/tags')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
